### ISSUE TITLE
"5 minutes for Chromium-based browsers."

### ISSUE THREAD

**Issue by guest271314** [jeremyckahn/secure-file-transfer#2]
There are exemptions for that 5 minutes and workarounds. An active Native Messaging connection extends the `ServiceWorker`  lifetime indefinitely. Passing messages as described in StreamSaver README; a never ending request keeps the `ServiceWorker` active indefinitely, too; see https://github.com/guest271314/persistent-serviceworker.

**Comment by jeremyckahn** [comment]
Thanks for sharing this, @guest271314! This is very cool. 🙂

Is the idea to incorporate something like the code at https://github.com/guest271314/persistent-serviceworker/tree/main/event-source-fetch-event to prevent the Service Worker from closing? If so, this seems like something that would ideally be implemented upstream in https://github.com/jimmywarting/StreamSaver.js/, rather than `secure-file-transfer`. Does that seem right to you?

**Comment by guest271314** [comment]
I am really just sharing the fact with you that claim in your README is not entirely true and correct, e.g., https://bugs.chromium.org/p/chromium/issues/detail?id=1189678, https://github.com/GoogleChrome/developer.chrome.com/issues/2688. There are exceptions per Chrome and several workarounds that you can select one to use from the linked repository, or roll your own. I published multiple approaches to hedge against Chromium authors changing their mind mid-stream to try to set the `ServiceWorker` to inactive after N time.

**Comment by guest271314** [comment]
You'll notice Chrome banned me from contributing in their repositories. So did Deno, et al. I'm a stickler about claims in documentation. I vet all claims no matter who the party is. I don't settle.

**Comment by jeremyckahn** [comment]
Got it. I'll do some experimentation to see if a workaround can be incorporated in either StreamSaver.js or `secure-file-transfer`. It looks like [some work has already been done upstream](https://github.com/jimmywarting/StreamSaver.js/blob/5b9ef44b8b388ee95aae0f0b2feb5be5830b9463/mitm.html#L16-L26), but it doesn't seem to be working in Firefox for me. I'll spend some time to see if a simple solution for SFT users can be implemented that works cross-browser.

**Comment by guest271314** [comment]
I mainly created this issue to advise you the claim in your README is not true and correct. There are exceptions. I appreciate the work that has gone in to StreamSaver.js. I don't really use that software though. I use extensions and Native Messaging extensively and other approaches for such tasks. File System Access API (formerly Native File System) is now implemented in Chromium/Chrome. Technically we can use WebRTC to "send" a file (WebRTC data channels do not actually _transfer_ the data in the sense of the later transferable objects), and "transfer" the file in the sense of Transferable Objects when we use resizable `ArrayBuffer` to store on one side then resize to 0 when the sending is complete, e.g., https://github.com/guest271314/offscreen-webrtc.

**Comment by guest271314** [comment]
The cross browser solution is to use `EventSource` and `onfetch` to make a never-ending request to the `ServiceWorker` https://github.com/guest271314/persistent-serviceworker/tree/main/message-event. Each folder in the reposiory is a different approach. I suggest testing them all if you intend to use a means to keep the `ServiceWorker` active greater than the arbitrary time vendors set on the implementation.

**Comment by jeremyckahn** [comment]
> The cross browser solution is to use `EventSource` and `onfetch` to make a never-ending request to the `ServiceWorker` https://github.com/guest271314/persistent-serviceworker/tree/main/message-event. Each folder in the reposiory is a different approach. I suggest testing them all if you intend to use a means to keep the `ServiceWorker` active greater than the arbitrary time vendors set on the implementation.

This is what I'm most interested in. Thank you for sharing this @guest271314! SFT should "just work" for all users of the library regardless of what browser they use. I'll explore how your work at https://github.com/guest271314/persistent-serviceworker/tree/main/message-event could be incorporated in SFT, if that's all right with you?

**Comment by jeremyckahn** [comment]
@guest271314 it turns out that StreamSaver.js utilizes keepalive logic as you described. However, it was erroneously disabled in some environments, and that led me to believe that it wasn't a workable solution at all. https://github.com/jimmywarting/StreamSaver.js/pull/305 closes this gap, and #4 updates SFT's README to remove the references to the problematic behavior that is no longer relevant.

Thank you for bringing this up and prompting me to dig into the issue! 🙂

**Comment by guest271314** [comment]
> to the problematic behavior that is no longer relevant

Have you tested to verify?

**Comment by jeremyckahn** [comment]
> Have you tested to verify?

Yep, I am able to successfully download files on Firefox that require StreamSaver’s file writing stream to stay open for well over 30 seconds. You can test it out for yourself at https://chitchatter.im/ by performing a transfer of a very large file (at least 2GB).

**Comment by guest271314** [comment]
That approach uses `onmessage`  and `postMessage()`, or `fetch` or `EventSource` and `respondWith()` passing a `ReadableStream`?

Technically a never ending stream from the `ServiceWorker` should keep it alive indefinitely. The service worker is doing work. As observed here https://github.com/jimmywarting/StreamSaver.js/pull/305#issuecomment-1444653584. That is not the case on Firefox Nightly 112, which without. This https://plnkr.co/edit/bK1BfoSgjFUDwkIV?preview has worked on Chromium Dev channel for a couple years now.

**Comment by jeremyckahn** [comment]
> That approach uses `onmessage` and `postMessage()`, or `fetch` or `EventSource` and `respondWith()` passing a `ReadableStream`?

It appears that StreamSaver.js's keepalive functionality utilizes a variety of mechanisms, depending on the situation: 
  - https://github.com/jimmywarting/StreamSaver.js/blob/34ea69ee90879d70c98514b5ef35371b50b7b0f0/mitm.html#L16-L26
  - https://github.com/jimmywarting/StreamSaver.js/blob/34ea69ee90879d70c98514b5ef35371b50b7b0f0/mitm.html#L142-L146
  - https://github.com/jimmywarting/StreamSaver.js/blob/34ea69ee90879d70c98514b5ef35371b50b7b0f0/sw.js#L73-L129

> Technically a never ending stream from the `ServiceWorker` should keep it alive indefinitely. The service worker is doing work. As observed here [jimmywarting/StreamSaver.js#305 (comment)](https://github.com/jimmywarting/StreamSaver.js/pull/305#issuecomment-1444653584). That is not the case on Firefox Nightly 112, which without. This https://plnkr.co/edit/bK1BfoSgjFUDwkIV?preview has worked on Chromium Dev channel for a couple years now.

Would this indicate a Firefox-specific bug, you think?

**Comment by guest271314** [comment]
If this https://github.com/jimmywarting/StreamSaver.js/pull/305#issuecomment-1445186081 quote 

> "respond with a ReadableStream where the service worker dose not need to do anything with it, can just be terminated and be pipe'ed in the background"

is the intended behaviour, and the approached used is transerring a stream to the service worker, and that is not happening in Firefox, yes. YMMV trying to convince specification authors or implementers it is. I would put the facts on the record nonetheless.

The alleged concern specification-wise is "event-driven" `ServiceWorker` should not remain active to conserve resources; I think primary for mobile devices on batteries, desktops not running on batteries are not really calculated into that equation obviously. Of course such a consideration is cancelled by the in-the-field use cases which need to use persistent code that would not otherwsie be used to keep the `ServiceWorker` active, a net gain of null. An exception on Chrome is using Native Messaging. But we have to watch and vet those claims from vendors as well (see link above in Google Chrome Developers repository).

You got your code working in Firefox anyway, right?

There are multiple ways to achieve your requirement, and multiple ways to keep a `ServiceWorker` active indefinitely on both Firefox and Chrome. Technically since you are not using extension `ServiceWorker` you could explore `BackgroundFetch` which does not work in extension `ServiceWorker`s. Choose the least vendor-restrictive for the environment.

**Comment by guest271314** [comment]
> Would this indicate a Firefox-specific bug, you think?

This works out of the box on Chromium 113 Dev Channel - an indeterminate response from a `fetch()` request made by a `WindowClient` of the `ServiceWorker`. To get the same behaviour on Firefox Nightly 112 a user can set `dom.serviceWorkers.idle_timeout` to something like `86400000` (`86400000/60/60/1000 // 24 hours`) so the "bug" part can interpreted as a configuration option available to the user by the application.

```
const start = new Date();

self.addEventListener('install', (event) => {
  console.log(event);
  event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});

self.addEventListener('fetch', async (event) => {
  console.log(event.request);
  if (event.request.url.endsWith('stream')) {
    return event.respondWith(
      new Response(
        new ReadableStream({
          start(c) {
            return console.log('Response stream started');
          },
          async pull(c) {
            c.enqueue(`${(new Date() - start) / 60000}`);
            await new Promise((r) => setTimeout(r, 15000));
          },
          cancel(reason = 'Client aborted stream') {
            console.log(reason);
          },
        }).pipeThrough(new TextEncoderStream())
      )
    );
  }
});
```

```
<script type="module">
      for (const registration of await navigator.serviceWorker.getRegistrations()) {
        console.log(registration);
        try {
          await registration.unregister();
        } catch (e) {
          throw e;
        }
      }
      const sw = await navigator.serviceWorker.register(
        `./sw.js?=${new Date().getTime()}`,
        {
          scope: './',
          // type: 'module',
          updateViaCache: 'none',
        }
      );
      await navigator.serviceWorker.ready;
      document.querySelector('h1').onclick = async (e) => {
        let ac = new AbortController();
        let { signal } = ac;
        fetch('./stream', {
          cache: 'no-store',
          signal,
        })
          .then((r) => {
            return r.body.pipeThrough(new TextDecoderStream()).pipeTo(
              new WritableStream({
                write(v) {
                  console.log(v);
                },
                close() {
                  console.log('close');
                },
                abort(reason) {
                  console.log({
                    reason,
                  });
                },
              })
            );
          })
          .catch(console.error);
      };
    </script>
```

**Comment by jeremyckahn** [comment]
Interesting. Thanks for the breakdown, @guest271314! So it may not be a "bug" in Firefox as much as it is an unhelpful default configuration. Typical users probably aren't likely to change such configuration. Considering that, this should be treated as standard Firefox behavior. 😕

**Comment by guest271314** [comment]
> Typical users probably aren't likely to change such configuration. 

If you provide a conspicuous notice with instructions they will. The use case here is "secure" file transfer. I don't think "typical" users are doing that. So if they are interested in that functionality they are probably aware of `about:config` in Firefox and will know the exact setting to change for the expected result to be achieved on Firefox.

**Comment by jeremyckahn** [comment]
> If you provide a conspicuous notice with instructions they will.

It doesn't seem reasonable to expect users to make an `about:config` change in order to use a web app. Especially for a generic library like SFT, things should "just work" for people without them having to think about it or be aware of any implementation details. Incorporating inelegant internal workarounds (like pinging the Service Worker to keep the connection alive) seems like a more user-friendly solution to this problem.

**Comment by guest271314** [comment]
> It doesn't seem reasonable to expect users to make an `about:config` change in order to use a web app. 

That happns all of the time in Chromium or Chrome based browsers. That is how Direct Sockets API is enabled.

It's you gear. I am just conveying my thoughts on the matter.
